Revert "Silence compiler warning if DEBUG is off."
priv is used again without DEBUG since 55ef4e1ad841dda08161009.
"Revert "Don't pass the axes around to sendCommon() and friends."

This fixes the following build error with --disable-debug:
wcmCommon.c: In function ‘sendWheelStripEvents’:
wcmCommon.c:671: error: ‘priv’ undeclared (first use in this function)
wcmCommon.c:671: error: (Each undeclared identifier is reported only once
wcmCommon.c:671: error: for each function it appears in.)

This reverts commit 8f69888a353e75a41abc90e85fba61805b9b97bd.

Conflicts:

	src/wcmCommon.c

Signed-off-by: Peter Hutterer <peter.hutterer@who-t.net>