Fix build error with --enable-debug.
Introduced with 09e01eda07de "Call wcmRotateCoordinates only when we get
real motion events".

wcmCommon.c: In function ‘wcmSoftOutEvent’:
wcmCommon.c:1646: error: invalid use of void expression

This patch also changes the message to the usual DBG format (the DBG macro
will fill in the device name and the function name automatically).

Signed-off-by: Peter Hutterer <peter.hutterer@who-t.net>
Acked-by: Ping Cheng <pinglinux@gmail.com>