meson.build: pass -Wno-error=format to the asprintf check
meson generates a little program containing "return asprintf ();"
But that call errors out, not because asprintf is missing but because on
clang, -Werror includes -Wformat:
	error: format string missing [-Werror,-Wformat]

The result is that meson things asprintf doesn't exist and we then try
to link to Xasprintf which is implemented in the server only (and thus
causes a linker error in the gwacom lib).

Signed-off-by: Peter Hutterer <peter.hutterer@who-t.net>