Move 'suppress' variable from wcmEvent to commonDispatchDevice
Resolves the following compile-time warning:

../src/wcmCommon.c: In function ‘wcmEvent’:
../src/wcmCommon.c:1007:23: error: ‘suppress’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
   commonDispatchDevice(pInfo, pChannel, suppress);
                       ^

Fixes: 2fa4ef48c9 ("Do not overwrite raw device state with filtered coordinate values")
Signed-off-by: Jason Gerecke <jason.gerecke@wacom.com>